In [1]:
import pandas as pd
import glob
import os
# read file from Bike share csv
path = r'D:\bootcamp\week_20_Final_Project\BIke sharing\Bike data'                    
all_files = glob.glob(os.path.join(path, "*.csv"))

# read each csv file and concatenate it into one dataframe
df_from_each_file = (pd.read_csv(f,encoding='latin-1') for f in all_files)
concatenated_df   = pd.concat(df_from_each_file, ignore_index=True)

In [2]:
concatenated_df.head()

,ï»¿Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type,Trip Id
0,4581278.0,1547.0,7021,01/01/2019 00:08,Bay St / Albert St,7233,01/01/2019 00:33,King / Cowan Ave - SMART,1296,Annual Member,NaN
1,4581279.0,1112.0,7160,01/01/2019 00:10,King St W / Tecumseth St,7051,01/01/2019 00:29,Wellesley St E / Yonge St (Green P),2947,Annual Member,NaN
2,4581280.0,589.0,7055,01/01/2019 00:15,Jarvis St / Carlton St,7013,01/01/2019 00:25,Scott St / The Esplanade,2293,Annual Member,NaN
3,4581281.0,259.0,7012,01/01/2019 00:16,Elizabeth St / Edward St (Bus Terminal),7235,01/01/2019 00:20,Bay St / College St (West Side) - SMART,283,Annual Member,NaN
4,4581282.0,281.0,7041,01/01/2019 00:19,Edward St / Yonge St,7257,01/01/2019 00:24,Dundas St W / St. Patrick St,1799,Annual Member,NaN

In [3]:
#delete na row

concatenated_df.dropna(subset = ['User Type'], inplace=True)#249 rows

In [4]:
concatenated_df.dtypes

ï»¿Trip Id            float64
Trip  Duration        float64
Start Station Id       object
Start Time             object
Start Station Name     object
End Station Id         object
End Time               object
End Station Name       object
Bike Id                object
User Type              object
Trip Id               float64
dtype: object

In [5]:
# drop if there is na data and check if there is still na data

concatenated_df.dropna(subset = ['Trip  Duration'], inplace=True)
concatenated_df[concatenated_df['Trip  Duration'].isna()]

Empty DataFrame
Columns: [ï»¿Trip Id, Trip  Duration, Start Station Id, Start Time, Start Station Name, End Station Id, End Time, End Station Name, Bike Id, User Type, Trip Id]
Index: []

In [6]:
# change datetype from datetime to date
concatenated_df['Date']=pd.to_datetime(concatenated_df['Start Time']).dt.date

In [33]:
#check start station id =na 
concatenated_df[concatenated_df['Start Station Id'].isna()]

Empty DataFrame
Columns: [ï»¿Trip Id, Trip  Duration, Start Station Id, Start Time, Start Station Name, End Station Id, End Time, End Station Name, Bike Id, User Type, Trip Id, Date]
Index: []

In [56]:
# copy to another dataframe 
clean_df2=concatenated_df

In [58]:
#fill End station=start station if end station id =na

clean_df2['End Station Id'] = clean_df2['End Station Id'].fillna(clean_df2['Start Station Id'])

clean_df2

,ï»¿Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type,Trip Id,Date
0,4581278.0,1547.0,7021,01/01/2019 00:08,Bay St / Albert St,7233,01/01/2019 00:33,King / Cowan Ave - SMART,1296,Annual Member,NaN,2019-01-01
1,4581279.0,1112.0,7160,01/01/2019 00:10,King St W / Tecumseth St,7051,01/01/2019 00:29,Wellesley St E / Yonge St (Green P),2947,Annual Member,NaN,2019-01-01
2,4581280.0,589.0,7055,01/01/2019 00:15,Jarvis St / Carlton St,7013,01/01/2019 00:25,Scott St / The Esplanade,2293,Annual Member,NaN,2019-01-01
3,4581281.0,259.0,7012,01/01/2019 00:16,Elizabeth St / Edward St (Bus Terminal),7235,01/01/2019 00:20,Bay St / College St (West Side) - SMART,283,Annual Member,NaN,2019-01-01
4,4581282.0,281.0,7041,01/01/2019 00:19,Edward St / Yonge St,7257,01/01/2019 00:24,Dundas St W / St. Patrick St,1799,Annual Member,NaN,2019-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...
8926002,14805103.0,372.0,7065,12/31/2021 23:56,Dundas St E / Parliament St,7472.0,01/01/2022 00:02,Dundas St E / Victoria St,3487,Casual Member,NaN,2021-12-31
8926003,14805104.0,762.0,7233,12/31/2021 23:56,King / Cowan Ave - SMART,7569.0,01/01/2022 00:08,Toronto Inukshuk Park,4195,Annual Member,NaN,2021-12-31
8926004,14805105.0,355.0,7065,12/31/2021 23:56,Dundas St E / Parliament St,7472.0,01/01/2022 00:02,Dundas St E / Victoria St,4574,Casual Member,NaN,2021-12-31
8926005,14805107.0,770.0,7292,12/31/2021 23:56,Granby St / Church St - SMART,7076.0,01/01/2022 00:09,York St / Queens Quay W,5879,Annual Member,NaN,2021-12-31
8926006,14805108.0,1307.0,7057,12/31/2021 23:59,Simcoe St / Wellington St South,7383.0,01/01/2022 00:21,12 Harbour St,1655,Annual Member,NaN,2021-12-31

In [60]:
#check end station id= na 
clean_df2[clean_df2['End Station Id'].isna()]

Empty DataFrame
Columns: [ï»¿Trip Id, Trip  Duration, Start Station Id, Start Time, Start Station Name, End Station Id, End Time, End Station Name, Bike Id, User Type, Trip Id, Date]
Index: []

In [61]:
# Convert station id to float to make all of the column has same datatype
clean_df2['Start Station Id']=clean_df2['Start Station Id'].astype(str).astype('float64')
clean_df2['End Station Id']=clean_df2['End Station Id'].astype(str).astype('float64')

In [64]:
#check unique value on start station 
clean_df2['Start Station Id'].nunique()

633

In [65]:
#check unique value for end station 
clean_df2['End Station Id'].nunique()

633

In [75]:
# open station file 
import json
with open('station_information.json', 'r') as f:
    data = json.load(f)['data']['stations']
Station_info_df = pd.DataFrame(data)

In [80]:
#covert station id type to float
Station_info_df['station_id']=Station_info_df['station_id'].astype(str).astype('float64')

In [81]:
# pick necessary column 
Station_info_df=Station_info_df[['station_id','name','lat','lon']]

In [82]:
#Merge to clean df to make sure all the station name will be the same 
Merged_station_data_df=pd.merge(clean_df2,Station_info_df,left_on='Start Station Id', right_on='station_id',how='left')
Merged_station_data_df

,ï»¿Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type,Trip Id,Date,station_id,name,lat,lon
0,4581278.0,1547.0,7021.0,01/01/2019 00:08,Bay St / Albert St,7233.0,01/01/2019 00:33,King / Cowan Ave - SMART,1296,Annual Member,NaN,2019-01-01,7021.0,Bay St / Albert St,43.653264,-79.382458
1,4581279.0,1112.0,7160.0,01/01/2019 00:10,King St W / Tecumseth St,7051.0,01/01/2019 00:29,Wellesley St E / Yonge St (Green P),2947,Annual Member,NaN,2019-01-01,7160.0,King St W / Tecumseth St,43.643333,-79.405556
2,4581280.0,589.0,7055.0,01/01/2019 00:15,Jarvis St / Carlton St,7013.0,01/01/2019 00:25,Scott St / The Esplanade,2293,Annual Member,NaN,2019-01-01,7055.0,Jarvis St / Carlton St,43.662070,-79.376170
3,4581281.0,259.0,7012.0,01/01/2019 00:16,Elizabeth St / Edward St (Bus Terminal),7235.0,01/01/2019 00:20,Bay St / College St (West Side) - SMART,283,Annual Member,NaN,2019-01-01,7012.0,Elizabeth St / Edward St (Bus Terminal),43.656026,-79.385327
4,4581282.0,281.0,7041.0,01/01/2019 00:19,Edward St / Yonge St,7257.0,01/01/2019 00:24,Dundas St W / St. Patrick St,1799,Annual Member,NaN,2019-01-01,7041.0,Edward St / Yonge St,43.656729,-79.382736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8925737,14805103.0,372.0,7065.0,12/31/2021 23:56,Dundas St E / Parliament St,7472.0,01/01/2022 00:02,Dundas St E / Victoria St,3487,Casual Member,NaN,2021-12-31,7065.0,Dundas St E / Parliament St,43.659575,-79.365769
8925738,14805104.0,762.0,7233.0,12/31/2021 23:56,King / Cowan Ave - SMART,7569.0,01/01/2022 00:08,Toronto Inukshuk Park,4195,Annual Member,NaN,2021-12-31,7233.0,King / Cowan Ave - SMART,43.637922,-79.431734
8925739,14805105.0,355.0,7065.0,12/31/2021 23:56,Dundas St E / Parliament St,7472.0,01/01/2022 00:02,Dundas St E / Victoria St,4574,Casual Member,NaN,2021-12-31,7065.0,Dundas St E / Parliament St,43.659575,-79.365769
8925740,14805107.0,770.0,7292.0,12/31/2021 23:56,Granby St / Church St - SMART,7076.0,01/01/2022 00:09,York St / Queens Quay W,5879,Annual Member,NaN,2021-12-31,7292.0,Granby St / Church St - SMART,43.661460,-79.378946
8925741,14805108.0,1307.0,7057.0,12/31/2021 23:59,Simcoe St / Wellington St South,7383.0,01/01/2022 00:21,12 Harbour St,1655,Annual Member,NaN,2021-12-31,7057.0,Simcoe St / Wellington St South,43.645857,-79.385365

In [86]:
#fillna if there is no  start station name in raw data using station name in Station_info_df
Merged_station_data_df['Start Station Name'] = Merged_station_data_df['Start Station Name'].fillna(Merged_station_data_df['name'])
Merged_station_data_df[Merged_station_data_df['Start Station Name'].isna()]

Empty DataFrame
Columns: [ï»¿Trip Id, Trip  Duration, Start Station Id, Start Time, Start Station Name, End Station Id, End Time, End Station Name, Bike Id, User Type, Trip Id, Date, station_id, name, lat, lon]
Index: []

In [95]:
#Check if there is any start station in raw data that doesn't have any info in Station_info_df 
Start_station_missing_df=Merged_station_data_df[Merged_station_data_df['name'].isna()]
Start_station_missing_df= Start_station_missing_df.drop_duplicates(['Start Station Id','Start Station Name'])[['Start Station Id','Start Station Name']]
Start_station_missing_df

         Start Station Id                             Start Station Name
90                 7051.0            Wellesley St E / Yonge St (Green P)
198                7254.0                 Borden St / Bloor St W - SMART
668                7116.0                     Parliament St / Bloor St E
1052               7358.0  Gailbraith Rd / Kingâs College Cr. (U of T)
666881             7393.0                      55 Magnificent Rd. Garage
732414             7219.0                                Wolfpack - 7219
897401             7402.0                  Wellington St W / Bathurst St
916314             7470.0                    York St / Lake Shore Blvd W
924543             7436.0                            Shaw St / Dupont St
926900             7456.0              Belmont St / Davenport Rd - SMART
953178             7481.0         Westmount Ave / St Clair Ave W - SMART
994093             7218.0                          Make Invisible - 7218
1103727            7510.0                      Princes Gate / Nunavut Dr
1229299            7394.0                              Toronto Bike Shop
1911858            7511.0                                       PBSC-OPS
3126977            7532.0                    135 Queenâs Wharf - SMART
3223090            7573.0                    Torrens Ave / Broadview Ave
4340430            7649.0                       Greenwood Subway Station
4539113            7651.0                     Bloor St W / Gladstone Ave
5353548            7358.0    Gailbraith Rd / Kings College Cr. (U of T)
5437097            7051.0                          Mutual St / Shuter St
5437586            7358.0  Gailbraith Rd / KingGÇÖs College Cr. (U of T)
5438388            7649.0               Greenwood Subway Station - SMART

In [98]:
#change column name for end station
Station_info_df.columns=['end_stat_id','end_name','end_lat','end_lon']
Station_info_df

     end_stat_id                      end_name    end_lat    end_lon
0         7000.0  Fort York  Blvd / Capreol Ct  43.639832 -79.395954
1         7001.0     Wellesley Station Green P  43.664964 -79.383550
2         7002.0    St. George St / Bloor St W  43.667333 -79.399429
3         7003.0      Madison Ave / Bloor St W  43.667158 -79.402761
4         7004.0       University Ave / Elm St  43.656518 -79.389099
..           ...                           ...        ...        ...
610       7685.0                  King / Brant  43.645102 -79.397450
611       7686.0  Lower Jarvis / The Esplanade  43.647821 -79.370472
612       7687.0     Bloor / Gladstone - SMART  43.660202 -79.434273
613       7688.0  High Park Blvd / Parkside Dr  43.644887 -79.456412
614       7689.0                      20 Eaton  43.680012 -79.344033

[615 rows x 4 columns]

In [99]:
# merge to raw data using end station as key 
Merged_station_data_df=pd.merge(Merged_station_data_df,Station_info_df,left_on='End Station Id', right_on='end_stat_id',how='left')
Merged_station_data_df

,ï»¿Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type,Trip Id,Date,station_id,name,lat,lon,end_stat_id,end_name,end_lat,end_lon
0,4581278.0,1547.0,7021.0,01/01/2019 00:08,Bay St / Albert St,7233.0,01/01/2019 00:33,King / Cowan Ave - SMART,1296,Annual Member,NaN,2019-01-01,7021.0,Bay St / Albert St,43.653264,-79.382458,7233.0,King / Cowan Ave - SMART,43.637922,-79.431734
1,4581279.0,1112.0,7160.0,01/01/2019 00:10,King St W / Tecumseth St,7051.0,01/01/2019 00:29,Wellesley St E / Yonge St (Green P),2947,Annual Member,NaN,2019-01-01,7160.0,King St W / Tecumseth St,43.643333,-79.405556,NaN,NaN,NaN,NaN
2,4581280.0,589.0,7055.0,01/01/2019 00:15,Jarvis St / Carlton St,7013.0,01/01/2019 00:25,Scott St / The Esplanade,2293,Annual Member,NaN,2019-01-01,7055.0,Jarvis St / Carlton St,43.662070,-79.376170,7013.0,Scott St / The Esplanade,43.646560,-79.375274
3,4581281.0,259.0,7012.0,01/01/2019 00:16,Elizabeth St / Edward St (Bus Terminal),7235.0,01/01/2019 00:20,Bay St / College St (West Side) - SMART,283,Annual Member,NaN,2019-01-01,7012.0,Elizabeth St / Edward St (Bus Terminal),43.656026,-79.385327,7235.0,Bay St / College St (West Side) - SMART,43.660087,-79.385655
4,4581282.0,281.0,7041.0,01/01/2019 00:19,Edward St / Yonge St,7257.0,01/01/2019 00:24,Dundas St W / St. Patrick St,1799,Annual Member,NaN,2019-01-01,7041.0,Edward St / Yonge St,43.656729,-79.382736,7257.0,Dundas St W / St. Patrick St,43.654517,-79.389532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8925737,14805103.0,372.0,7065.0,12/31/2021 23:56,Dundas St E / Parliament St,7472.0,01/01/2022 00:02,Dundas St E / Victoria St,3487,Casual Member,NaN,2021-12-31,7065.0,Dundas St E / Parliament St,43.659575,-79.365769,7472.0,Dundas St E / Victoria St,43.656311,-79.379158
8925738,14805104.0,762.0,7233.0,12/31/2021 23:56,King / Cowan Ave - SMART,7569.0,01/01/2022 00:08,Toronto Inukshuk Park,4195,Annual Member,NaN,2021-12-31,7233.0,King / Cowan Ave - SMART,43.637922,-79.431734,7569.0,Toronto Inukshuk Park,43.632399,-79.409782
8925739,14805105.0,355.0,7065.0,12/31/2021 23:56,Dundas St E / Parliament St,7472.0,01/01/2022 00:02,Dundas St E / Victoria St,4574,Casual Member,NaN,2021-12-31,7065.0,Dundas St E / Parliament St,43.659575,-79.365769,7472.0,Dundas St E / Victoria St,43.656311,-79.379158
8925740,14805107.0,770.0,7292.0,12/31/2021 23:56,Granby St / Church St - SMART,7076.0,01/01/2022 00:09,York St / Queens Quay W,5879,Annual Member,NaN,2021-12-31,7292.0,Granby St / Church St - SMART,43.661460,-79.378946,7076.0,York St / Queens Quay W,43.640132,-79.380464
8925741,14805108.0,1307.0,7057.0,12/31/2021 23:59,Simcoe St / Wellington St South,7383.0,01/01/2022 00:21,12 Harbour St,1655,Annual Member,NaN,2021-12-31,7057.0,Simcoe St / Wellington St South,43.645857,-79.385365,7383.0,12 Harbour St,43.642564,-79.376200

In [100]:
#fillna if there is no  end station name in raw data using station name in station_df
Merged_station_data_df['End Station Name'] = Merged_station_data_df['End Station Name'].fillna(Merged_station_data_df['end_name'])
Merged_station_data_df[Merged_station_data_df['End Station Name'].isna()]

,ï»¿Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type,Trip Id,Date,station_id,name,lat,lon,end_stat_id,end_name,end_lat,end_lon
2154817,7002115.0,950.0,7051.0,10/23/2019 07:01,Wellesley St E / Yonge St (Green P),7051.0,10/23/2019 07:16,NaN,2996,Annual Member,NaN,2019-10-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2189589,7041467.0,936.0,7470.0,10/27/2019 14:42,York St / Lake Shore Blvd W,7470.0,10/27/2019 14:57,NaN,1822,Annual Member,NaN,2019-10-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2277171,7142444.0,652.0,7402.0,11/13/2019 09:48,Wellington St W / Bathurst St,7402.0,11/13/2019 09:59,NaN,3808,Annual Member,NaN,2019-11-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2277286,7142590.0,508.0,7051.0,11/13/2019 10:52,Wellesley St E / Yonge St (Green P),7051.0,11/13/2019 11:00,NaN,3007,Annual Member,NaN,2019-11-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2286314,7153321.0,1200.0,7254.0,11/16/2019 09:36,Borden St / Bloor St W - SMART,7254.0,11/16/2019 09:56,NaN,4041,Annual Member,NaN,2019-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2357880,7237090.0,1551.0,7470.0,12/02/2019 09:13,York St / Lake Shore Blvd W,7470.0,12/02/2019 09:39,NaN,5000,Annual Member,NaN,2019-12-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2413069,7303320.0,1458.0,7402.0,12/19/2019 09:26,Wellington St W / Bathurst St,7402.0,12/19/2019 09:50,NaN,1626,Annual Member,NaN,2019-12-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2430428,7323325.0,1721.0,7051.0,12/27/2019 15:28,Wellesley St E / Yonge St (Green P),7051.0,12/27/2019 15:57,NaN,4977,Annual Member,NaN,2019-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2487391,7391142.0,1359.0,7358.0,01/15/2020 15:28,Gailbraith Rd / Kingâs College Cr. (U of T),7358.0,01/15/2020 15:50,NaN,3422,Annual Member,NaN,2020-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2500677,7406213.0,1020.0,7358.0,01/20/2020 17:12,Gailbraith Rd / Kingâs College Cr. (U of T),7358.0,01/20/2020 17:29,NaN,3904,Annual Member,NaN,2020-01-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2595866,7514620.0,900.0,7470.0,02/18/2020 21:05,York St / Lake Shore Blvd W,7470.0,02/18/2020 21:20,NaN,4624,Annual Member,NaN,2020-02-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2723979,7663220.0,1298.0,7470.0,03/22/2020 14:38,York St / Lake Shore Blvd W,7470.0,03/22/2020 15:00,NaN,1683,Annual Member,NaN,2020-03-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2810170,7770174.0,27065.0,7051.0,04/29/2020 06:01,Wellesley St E / Yonge St (Green P),7051.0,04/29/2020 13:33,NaN,2156,Casual Member,NaN,2020-04-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2990409,7980056.0,720.0,7436.0,05/30/2020 15:14,Shaw St / Dupont St,7436.0,05/30/2020 15:26,NaN,3886,Annual Member,NaN,2020-05-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3008375,7999589.0,1772.0,7456.0,05/31/2020 18:59,Belmont St / Davenport Rd - SMART,7456.0,05/31/2020 19:28,NaN,1052,Annual Member,NaN,2020-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3986243,9085997.0,0.0,7051.0,08/10/2020 18:20,Wellesley St E / Yonge St (Green P),7051.0,08/10/2020 18:20,NaN,216,Annual Member,NaN,2020-08-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3986248,9086005.0,0.0,7051.0,08/10/2020 18:21,Wellesley St E / Yonge St (Green P),7051.0,08/10/2020 18:21,NaN,2902,Annual Member,NaN,2020-08-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4051814,9162280.0,0.0,7254.0,08/14/2020 23:07,Borden St / Bloor St W - SMART,7254.0,08/14/2020 23:07,NaN,4486,Casual Member,NaN,2020-08-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4524656,9693253.0,0.0,7254.0,09/13/2020 13:07,Borden St / Bloor St W - SMART,7254.0,09/13/2020 13:07,NaN,6611,Casual Member,NaN,2020-09-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4525321,9694016.0,0.0,7051.0,09/13/2020 13:46,Wellesley St E / Yonge St (Green P),7051.0,09/13/2020 13:46,NaN,6886,Annual Member,NaN,2020-09-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4897484,10111974.0,0.0,7116.0,10/13/2020 12:00,Parliament St / Bloor St E,7116.0,10/13/2020 12:00,NaN,650,Annual Member,NaN,2020-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4906232,10121961.0,0.0,7470.0,10/14/2020 08:14,York St / Lake Shore Blvd W,7470.0,10/14/2020 08:14,NaN,5722,Annual Member,NaN,2020-10-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5132539,10387373.0,0.0,7116.0,11/09/2020 17:28,Parliament St / Bloor St E,7116.0,11/09/2020 17:28,NaN,4372,Casual Member,NaN,2020-11-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5222450,10492356.0,0.0,7254.0,11/23/2020 18:07,Borden St / Bloor St W - SMART,7254.0,11/23/2020 18:07,NaN,5927,Annual Member,NaN,2020-11-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5224355,10494642.0,0.0,7051.0,11/24/2020 11:10,Wellesley St E / Yonge St (Green P),7051.0,11/24/2020 11:10,NaN,4598,Casual Member,NaN,2020-11-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5224510,10494817.0,0.0,7254.0,11/24/2020 12:01,Borden St / Bloor St W - SMART,7254.0,11/24/2020 12:01,NaN,3085,Annual Member,NaN,2020-11-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5227792,10498502.0,0.0,7481.0,11/25/2020 08:54,Westmount Ave / St Clair Ave W - SMART,7481.0,11/25/2020 08:54,NaN,6852,Annual Member,NaN,2020-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5227968,10498730.0,0.0,7254.0,11/25/2020 09:37,Borden St / Bloor St W - SMART,7254.0,11/25/2020 09:37,NaN,2135,Casual Member,NaN,2020-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5229469,10500674.0,0.0,7470.0,11/25/2020 16:10,York St / Lake Shore Blvd W,7470.0,11/25/2020 16:10,NaN,2145,Annual Member,NaN,2020-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5254562,10529161.0,0.0,7051.0,11/30/2020 16:40,Wellesley St E / Yonge St (Green P),7051.0,11/30/2020 16:40,NaN,5787,Annual Member,NaN,2020-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5254949,10529591.0,0.0,7254.0,11/30/2020 19:12,Borden St / Bloor St W - SMART,7254.0,11/30/2020 19:12,NaN,3263,Annual Member,NaN,2020-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5308884,10594724.0,0.0,7470.0,12/16/2020 09:52,York St / Lake Shore Blvd W,7470.0,12/16/2020 09:52,NaN,6083.0,Annual Member,NaN,2020-12-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5350893,NaN,0.0,7470.0,01/01/2021 09:41,York St / Lake Shore Blvd W,7470.0,01/01/2021 09:41,NaN,5761.0,Annual Member,10644662.0,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5359393,NaN,0.0,7358.0,01/05/2021 06:50,Gailbraith Rd / Kings College Cr. (U of T),7358.0,01/05/2021 06:50,NaN,3153.0,Annual Member,10655032.0,2021-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5359527,NaN,0.0,7051.0,01/05/2021 07:59,Wellesley St E / Yonge St (Green P),7051.0,01/05/2021 07:59,NaN,5094.0,Casual Member,10655239.0,2021-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5361019,NaN,0.0,7051.0,01/05/2021 16:54,Wellesley St E / Yonge St (Green P),7051.0,01/05/2021 16:54,NaN,725.0,Annual Member,10657416.0,2021-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5365668,NaN,0.0,7254.0,01/07/2021 08:41,Borden St / Bloor St W - SMART,7254.0,01/07/2021 08:41,NaN,3623.0,Annual Member,10663126.0,2021-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5368958,NaN,0.0,7470.0,01/08/2021 07:09,York St / Lake Shore Blvd W,7470.0,01/08/2021 07:09,NaN,547.0,Casual Member,10667161.0,2021-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5376440,NaN,0.0,7116.0,01/10/2021 00:11,Parliament St / Bloor St E,7116.0,01/10/2021 00:11,NaN,4378.0,Casual Member,10675744.0,2021-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5376441,NaN,0.0,7116.0,01/10/2021 00:12,Parliament St / Bloor St E,7116.0,01/10/2021 00:12,NaN,3930.0,Annual Member,10675746.0,2021-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5421188,NaN,1340.0,7254.0,01/24/2021 08:23,Borden St / Bloor St W - SMART,7254.0,01/24/2021 08:45,NaN,911.0,Casual Member,10729533.0,2021-01-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5602267,NaN,0.0,7254.0,03/23/2021 17:49,Borden St / Bloor St W - SMART,7254.0,03/23/2021 17:49,NaN,1840,Annual Member,10954749.0,2021-03-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5619997,NaN,0.0,7651.0,03/26/2021 08:20,Bloor St W / Gladstone Ave,7651.0,03/26/2021 08:20,NaN,4730,Annual Member,10976147.0,2021-03-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5645499,NaN,0.0,7470.0,03/30/2021 18:35,York St / Lake Shore Blvd W,7470.0,03/30/2021 18:35,NaN,6413,Annual Member,11006590.0,2021-03-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5751826,NaN,0.0,7470.0,04/13/2021 13:47,York St / Lake Shore Blvd W,7470.0,04/13/2021 13:47,NaN,6774,Casual Member,11131935.0,2021-04-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5829482,NaN,0.0,7649.0,04/24/2021 14:14,Greenwood Subway Station - SMART,7649.0,04/24/2021 14:14,NaN,3436,Annual Member,11224466.0,2021-04-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5849263,NaN,0.0,7510.0,04/25/2021 18:06,Princes Gate / Nunavut Dr,7510.0,04/25/2021 18:06,NaN,6059,Annual Member,11246836.0,2021-04-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5849269,NaN,0.0,7510.0,04/25/2021 18:06,Princes Gate / Nunavut Dr,7510.0,04/25/2021 18:06,NaN,5487,Annual Member,11246842.0,2021-04-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5849273,NaN,0.0,7510.0,04/25/2021 18:06,Princes Gate / Nunavut Dr,7510.0,04/25/2021 18:06,NaN,6204,Annual Member,11246846.0,2021-04-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5918352,NaN,0.0,7051.0,05/06/2021 14:47,Mutual St / Shuter St,7051.0,05/06/2021 14:47,NaN,5028,Casual Member,11333568.0,2021-05-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6124497,NaN,0.0,7470.0,05/21/2021 16:46,York St / Lake Shore Blvd W,7470.0,05/21/2021 16:46,NaN,2417,Annual Member,11570591.0,2021-05-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6278009,NaN,0.0,7470.0,05/30/2021 16:48,York St / Lake Shore Blvd W,7470.0,05/30/2021 16:48,NaN,5079,Annual Member,11742753.0,2021-05-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6293249,NaN,0.0,7470.0,05/31/2021 15:13,York St / Lake Shore Blvd W,7470.0,05/31/2021 15:13,NaN,6550,Annual Member,11759823.0,2021-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6299907,NaN,0.0,7470.0,05/31/2021 20:26,York St / Lake Shore Blvd W,7470.0,05/31/2021 20:26,NaN,116,Casual Member,11766995.0,2021-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6838048,NaN,0.0,7051.0,07/06/2021 09:16,Mutual St / Shuter St,7051.0,07/06/2021 09:16,NaN,3894,Casual Member,12387325.0,2021-07-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6868959,NaN,0.0,7510.0,07/08/2021 21:02,Princes Gate / Nunavut Dr,7510.0,07/08/2021 21:02,NaN,3658,Annual Member,12423966.0,2021-07-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6870960,NaN,0.0,7470.0,07/09/2021 07:54,York St / Lake Shore Blvd W,7470.0,07/09/2021 07:54,NaN,4867,Annual Member,12426563.0,2021-07-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7352033,NaN,0.0,7470.0,08/09/2021 09:35,York St / Lake Shore Blvd W,7470.0,08/09/2021 09:35,NaN,53,Casual Member,12976571.0,2021-08-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7628891,NaN,0.0,7051.0,08/26/2021 18:07,Mutual St / Shuter St,7051.0,08/26/2021 18:07,NaN,5414,Annual Member,13295721.0,2021-08-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8053366,NaN,0.0,7358.0,09/22/2021 13:03,Gailbraith Rd / KingGÇÖs College Cr. (U of T),7358.0,09/22/2021 13:03,NaN,2688,Annual Member,13781880.0,2021-09-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
#drop duplicates for end station
End_station_missing_df=Merged_station_data_df[Merged_station_data_df['end_name'].isna()|Merged_station_data_df['End Station Name'].isna()]
End_station_missing_df= End_station_missing_df.drop_duplicates(['End Station Id','End Station Name'])[['End Station Id','End Station Name']]
End_station_missing_df

         End Station Id                               End Station Name
1                7051.0            Wellesley St E / Yonge St (Green P)
85               7254.0                 Borden St / Bloor St W - SMART
230              7358.0  Gailbraith Rd / Kingâs College Cr. (U of T)
632              7116.0                     Parliament St / Bloor St E
465027           7394.0                              Toronto Bike Shop
666881           7219.0                                Wolfpack - 7219
743898           7218.0                          Make Invisible - 7218
896375           7402.0                  Wellington St W / Bathurst St
914694           7470.0                    York St / Lake Shore Blvd W
926168           7456.0              Belmont St / Davenport Rd - SMART
929704           7436.0                            Shaw St / Dupont St
957353           7481.0         Westmount Ave / St Clair Ave W - SMART
1103657          7510.0                      Princes Gate / Nunavut Dr
1911858          7511.0                                       PBSC-OPS
2154817          7051.0                                            NaN
2189589          7470.0                                            NaN
2277171          7402.0                                            NaN
2286314          7254.0                                            NaN
2487391          7358.0                                            NaN
2990409          7436.0                                            NaN
3008375          7456.0                                            NaN
3126660          7532.0                    135 Queenâs Wharf - SMART
3226610          7573.0                    Torrens Ave / Broadview Ave
4336585          7649.0                       Greenwood Subway Station
4538991          7651.0                     Bloor St W / Gladstone Ave
4897484          7116.0                                            NaN
4942697          7638.0                          Warehouse EBS-Station
5227792          7481.0                                            NaN
5352861          7358.0    Gailbraith Rd / Kings College Cr. (U of T)
5437210          7051.0                          Mutual St / Shuter St
5437255          7358.0  Gailbraith Rd / KingGÇÖs College Cr. (U of T)
5437917          7649.0               Greenwood Subway Station - SMART
5619997          7651.0                                            NaN
5829482          7649.0                                            NaN
5849263          7510.0                                            NaN
8427520          7481.0                 Westmount Ave / St Clair Ave W
8820972          7116.0                              555 Bloor St East

In [109]:
#all location missing from start station and end station 
End_station_missing_df.columns=['Start Station Id','Start Station Name']
All_Location = Start_station_missing_df.append(End_station_missing_df, ignore_index=True)
All_Location

    Start Station Id                             Start Station Name
0             7051.0            Wellesley St E / Yonge St (Green P)
1             7254.0                 Borden St / Bloor St W - SMART
2             7116.0                     Parliament St / Bloor St E
3             7358.0  Gailbraith Rd / Kingâs College Cr. (U of T)
4             7393.0                      55 Magnificent Rd. Garage
5             7219.0                                Wolfpack - 7219
6             7402.0                  Wellington St W / Bathurst St
7             7470.0                    York St / Lake Shore Blvd W
8             7436.0                            Shaw St / Dupont St
9             7456.0              Belmont St / Davenport Rd - SMART
10            7481.0         Westmount Ave / St Clair Ave W - SMART
11            7218.0                          Make Invisible - 7218
12            7510.0                      Princes Gate / Nunavut Dr
13            7394.0                              Toronto Bike Shop
14            7511.0                                       PBSC-OPS
15            7532.0                    135 Queenâs Wharf - SMART
16            7573.0                    Torrens Ave / Broadview Ave
17            7649.0                       Greenwood Subway Station
18            7651.0                     Bloor St W / Gladstone Ave
19            7358.0    Gailbraith Rd / Kings College Cr. (U of T)
20            7051.0                          Mutual St / Shuter St
21            7358.0  Gailbraith Rd / KingGÇÖs College Cr. (U of T)
22            7649.0               Greenwood Subway Station - SMART
23            7051.0            Wellesley St E / Yonge St (Green P)
24            7254.0                 Borden St / Bloor St W - SMART
25            7358.0  Gailbraith Rd / Kingâs College Cr. (U of T)
26            7116.0                     Parliament St / Bloor St E
27            7394.0                              Toronto Bike Shop
28            7219.0                                Wolfpack - 7219
29            7218.0                          Make Invisible - 7218
30            7402.0                  Wellington St W / Bathurst St
31            7470.0                    York St / Lake Shore Blvd W
32            7456.0              Belmont St / Davenport Rd - SMART
33            7436.0                            Shaw St / Dupont St
34            7481.0         Westmount Ave / St Clair Ave W - SMART
35            7510.0                      Princes Gate / Nunavut Dr
36            7511.0                                       PBSC-OPS
37            7051.0                                            NaN
38            7470.0                                            NaN
39            7402.0                                            NaN
40            7254.0                                            NaN
41            7358.0                                            NaN
42            7436.0                                            NaN
43            7456.0                                            NaN
44            7532.0                    135 Queenâs Wharf - SMART
45            7573.0                    Torrens Ave / Broadview Ave
46            7649.0                       Greenwood Subway Station
47            7651.0                     Bloor St W / Gladstone Ave
48            7116.0                                            NaN
49            7638.0                          Warehouse EBS-Station
50            7481.0                                            NaN
51            7358.0    Gailbraith Rd / Kings College Cr. (U of T)
52            7051.0                          Mutual St / Shuter St
53            7358.0  Gailbraith Rd / KingGÇÖs College Cr. (U of T)
54            7649.0               Greenwood Subway Station - SMART
55            7651.0                                            NaN
56            7649.0                                            NaN
57            7510.0                                            NaN
58            7481.0                 Westmount Ave / St Clair Ave W
59            7116.0                              555 Bloor St East

In [111]:
#delete duplicate nan
All_Location = All_Location[~All_Location['Start Station Id'].duplicated(keep=False) | All_Location[['Start Station Name']].notnull().any(axis=1)]
All_Location

    Start Station Id                             Start Station Name
0             7051.0            Wellesley St E / Yonge St (Green P)
1             7254.0                 Borden St / Bloor St W - SMART
2             7116.0                     Parliament St / Bloor St E
3             7358.0  Gailbraith Rd / Kingâs College Cr. (U of T)
4             7393.0                      55 Magnificent Rd. Garage
5             7219.0                                Wolfpack - 7219
6             7402.0                  Wellington St W / Bathurst St
7             7470.0                    York St / Lake Shore Blvd W
8             7436.0                            Shaw St / Dupont St
9             7456.0              Belmont St / Davenport Rd - SMART
10            7481.0         Westmount Ave / St Clair Ave W - SMART
11            7218.0                          Make Invisible - 7218
12            7510.0                      Princes Gate / Nunavut Dr
13            7394.0                              Toronto Bike Shop
14            7511.0                                       PBSC-OPS
15            7532.0                    135 Queenâs Wharf - SMART
16            7573.0                    Torrens Ave / Broadview Ave
17            7649.0                       Greenwood Subway Station
18            7651.0                     Bloor St W / Gladstone Ave
19            7358.0    Gailbraith Rd / Kings College Cr. (U of T)
20            7051.0                          Mutual St / Shuter St
21            7358.0  Gailbraith Rd / KingGÇÖs College Cr. (U of T)
22            7649.0               Greenwood Subway Station - SMART
49            7638.0                          Warehouse EBS-Station
58            7481.0                 Westmount Ave / St Clair Ave W
59            7116.0                              555 Bloor St East

In [112]:
#drop duplicates
All_Location= All_Location.drop_duplicates(['Start Station Id','Start Station Name'])[['Start Station Id','Start Station Name']]
All_Location

    Start Station Id                             Start Station Name
0             7051.0            Wellesley St E / Yonge St (Green P)
1             7254.0                 Borden St / Bloor St W - SMART
2             7116.0                     Parliament St / Bloor St E
3             7358.0  Gailbraith Rd / Kingâs College Cr. (U of T)
4             7393.0                      55 Magnificent Rd. Garage
5             7219.0                                Wolfpack - 7219
6             7402.0                  Wellington St W / Bathurst St
7             7470.0                    York St / Lake Shore Blvd W
8             7436.0                            Shaw St / Dupont St
9             7456.0              Belmont St / Davenport Rd - SMART
10            7481.0         Westmount Ave / St Clair Ave W - SMART
11            7218.0                          Make Invisible - 7218
12            7510.0                      Princes Gate / Nunavut Dr
13            7394.0                              Toronto Bike Shop
14            7511.0                                       PBSC-OPS
15            7532.0                    135 Queenâs Wharf - SMART
16            7573.0                    Torrens Ave / Broadview Ave
17            7649.0                       Greenwood Subway Station
18            7651.0                     Bloor St W / Gladstone Ave
19            7358.0    Gailbraith Rd / Kings College Cr. (U of T)
20            7051.0                          Mutual St / Shuter St
21            7358.0  Gailbraith Rd / KingGÇÖs College Cr. (U of T)
22            7649.0               Greenwood Subway Station - SMART
49            7638.0                          Warehouse EBS-Station
58            7481.0                 Westmount Ave / St Clair Ave W
59            7116.0                              555 Bloor St East

In [113]:
#check how many station is double
All_Location.groupby(['Start Station Id']).count()

                  Start Station Name
Start Station Id
7051.0                             2
7116.0                             2
7218.0                             1
7219.0                             1
7254.0                             1
7358.0                             3
7393.0                             1
7394.0                             1
7402.0                             1
7436.0                             1
7456.0                             1
7470.0                             1
7481.0                             2
7510.0                             1
7511.0                             1
7532.0                             1
7573.0                             1
7638.0                             1
7649.0                             2
7651.0                             1

In [114]:
# sort by station id
All_Location=All_Location.sort_values(by=['Start Station Id'])
All_Location

    Start Station Id                             Start Station Name
0             7051.0            Wellesley St E / Yonge St (Green P)
20            7051.0                          Mutual St / Shuter St
59            7116.0                              555 Bloor St East
2             7116.0                     Parliament St / Bloor St E
11            7218.0                          Make Invisible - 7218
5             7219.0                                Wolfpack - 7219
1             7254.0                 Borden St / Bloor St W - SMART
3             7358.0  Gailbraith Rd / Kingâs College Cr. (U of T)
21            7358.0  Gailbraith Rd / KingGÇÖs College Cr. (U of T)
19            7358.0    Gailbraith Rd / Kings College Cr. (U of T)
4             7393.0                      55 Magnificent Rd. Garage
13            7394.0                              Toronto Bike Shop
6             7402.0                  Wellington St W / Bathurst St
8             7436.0                            Shaw St / Dupont St
9             7456.0              Belmont St / Davenport Rd - SMART
7             7470.0                    York St / Lake Shore Blvd W
10            7481.0         Westmount Ave / St Clair Ave W - SMART
58            7481.0                 Westmount Ave / St Clair Ave W
12            7510.0                      Princes Gate / Nunavut Dr
14            7511.0                                       PBSC-OPS
15            7532.0                    135 Queenâs Wharf - SMART
16            7573.0                    Torrens Ave / Broadview Ave
49            7638.0                          Warehouse EBS-Station
17            7649.0                       Greenwood Subway Station
22            7649.0               Greenwood Subway Station - SMART
18            7651.0                     Bloor St W / Gladstone Ave

In [149]:
#save to csv
All_Location.to_csv('result/missing_station.csv',index=False)

In [150]:
# read missing_station_csv after some of the data is filled
additional_station_df=pd.read_csv('result/missing_station_filled.csv',encoding='latin-1')

In [151]:
#check datatype
additional_station_df.dtypes

Stat_id        int64
Stat_name     object
Latitude     float64
Langitude    float64
dtype: object

In [152]:
#convert datatype
additional_station_df['Stat_id']=additional_station_df['Stat_id'].astype(str).astype('float64')

In [153]:
#append the missing station to Station_info_df
Station_info_df.columns=['Stat_id','Stat_name','Latitude','Langitude']
additional_station_df = additional_station_df.append(Station_info_df, ignore_index=True)
additional_station_df

     Stat_id                            Stat_name   Latitude  Langitude
0     7051.0  Wellesley St E / Yonge St (Green P)  43.665100 -79.383800
1     7116.0           Parliament St / Bloor St E        NaN        NaN
2     7218.0                Make Invisible - 7218        NaN        NaN
3     7219.0                      Wolfpack - 7219        NaN        NaN
4     7254.0       Borden St / Bloor St W - SMART        NaN        NaN
..       ...                                  ...        ...        ...
630   7685.0                         King / Brant  43.645102 -79.397450
631   7686.0         Lower Jarvis / The Esplanade  43.647821 -79.370472
632   7687.0            Bloor / Gladstone - SMART  43.660202 -79.434273
633   7688.0         High Park Blvd / Parkside Dr  43.644887 -79.456412
634   7689.0                             20 Eaton  43.680012 -79.344033

[635 rows x 4 columns]

In [154]:
#merge to the raw data for start station , to filling up the missing station 
Merged_station_data_df=pd.merge(clean_df2,additional_station_df,left_on='Start Station Id', right_on='Stat_id',how='left')
Merged_station_data_df

,ï»¿Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type,Trip Id,Date,Stat_id,Stat_name,Latitude,Langitude
0,4581278.0,1547.0,7021.0,01/01/2019 00:08,Bay St / Albert St,7233.0,01/01/2019 00:33,King / Cowan Ave - SMART,1296,Annual Member,NaN,2019-01-01,7021.0,Bay St / Albert St,43.653264,-79.382458
1,4581279.0,1112.0,7160.0,01/01/2019 00:10,King St W / Tecumseth St,7051.0,01/01/2019 00:29,Wellesley St E / Yonge St (Green P),2947,Annual Member,NaN,2019-01-01,7160.0,King St W / Tecumseth St,43.643333,-79.405556
2,4581280.0,589.0,7055.0,01/01/2019 00:15,Jarvis St / Carlton St,7013.0,01/01/2019 00:25,Scott St / The Esplanade,2293,Annual Member,NaN,2019-01-01,7055.0,Jarvis St / Carlton St,43.662070,-79.376170
3,4581281.0,259.0,7012.0,01/01/2019 00:16,Elizabeth St / Edward St (Bus Terminal),7235.0,01/01/2019 00:20,Bay St / College St (West Side) - SMART,283,Annual Member,NaN,2019-01-01,7012.0,Elizabeth St / Edward St (Bus Terminal),43.656026,-79.385327
4,4581282.0,281.0,7041.0,01/01/2019 00:19,Edward St / Yonge St,7257.0,01/01/2019 00:24,Dundas St W / St. Patrick St,1799,Annual Member,NaN,2019-01-01,7041.0,Edward St / Yonge St,43.656729,-79.382736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8925737,14805103.0,372.0,7065.0,12/31/2021 23:56,Dundas St E / Parliament St,7472.0,01/01/2022 00:02,Dundas St E / Victoria St,3487,Casual Member,NaN,2021-12-31,7065.0,Dundas St E / Parliament St,43.659575,-79.365769
8925738,14805104.0,762.0,7233.0,12/31/2021 23:56,King / Cowan Ave - SMART,7569.0,01/01/2022 00:08,Toronto Inukshuk Park,4195,Annual Member,NaN,2021-12-31,7233.0,King / Cowan Ave - SMART,43.637922,-79.431734
8925739,14805105.0,355.0,7065.0,12/31/2021 23:56,Dundas St E / Parliament St,7472.0,01/01/2022 00:02,Dundas St E / Victoria St,4574,Casual Member,NaN,2021-12-31,7065.0,Dundas St E / Parliament St,43.659575,-79.365769
8925740,14805107.0,770.0,7292.0,12/31/2021 23:56,Granby St / Church St - SMART,7076.0,01/01/2022 00:09,York St / Queens Quay W,5879,Annual Member,NaN,2021-12-31,7292.0,Granby St / Church St - SMART,43.661460,-79.378946
8925741,14805108.0,1307.0,7057.0,12/31/2021 23:59,Simcoe St / Wellington St South,7383.0,01/01/2022 00:21,12 Harbour St,1655,Annual Member,NaN,2021-12-31,7057.0,Simcoe St / Wellington St South,43.645857,-79.385365

In [155]:
#fillna
Merged_station_data_df['Start Station Name'] = Merged_station_data_df['Start Station Name'].fillna(Merged_station_data_df['Stat_name'])
Merged_station_data_df[Merged_station_data_df['Start Station Name'].isna()]

Empty DataFrame
Columns: [ï»¿Trip Id, Trip  Duration, Start Station Id, Start Time, Start Station Name, End Station Id, End Time, End Station Name, Bike Id, User Type, Trip Id, Date, Stat_id, Stat_name, Latitude, Langitude]
Index: []

In [156]:
#change column name for end station 
additional_station_df.columns=['end_stat_id','end_name','end_lat','end_lon']
additional_station_df

     end_stat_id                             end_name    end_lat    end_lon
0         7051.0  Wellesley St E / Yonge St (Green P)  43.665100 -79.383800
1         7116.0           Parliament St / Bloor St E        NaN        NaN
2         7218.0                Make Invisible - 7218        NaN        NaN
3         7219.0                      Wolfpack - 7219        NaN        NaN
4         7254.0       Borden St / Bloor St W - SMART        NaN        NaN
..           ...                                  ...        ...        ...
630       7685.0                         King / Brant  43.645102 -79.397450
631       7686.0         Lower Jarvis / The Esplanade  43.647821 -79.370472
632       7687.0            Bloor / Gladstone - SMART  43.660202 -79.434273
633       7688.0         High Park Blvd / Parkside Dr  43.644887 -79.456412
634       7689.0                             20 Eaton  43.680012 -79.344033

[635 rows x 4 columns]

In [157]:
#merge to raw data using end station id as key
Merged_station_data_df=pd.merge(Merged_station_data_df,additional_station_df,left_on='End Station Id', right_on='end_stat_id',how='left')
Merged_station_data_df

,ï»¿Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type,Trip Id,Date,Stat_id,Stat_name,Latitude,Langitude,end_stat_id,end_name,end_lat,end_lon
0,4581278.0,1547.0,7021.0,01/01/2019 00:08,Bay St / Albert St,7233.0,01/01/2019 00:33,King / Cowan Ave - SMART,1296,Annual Member,NaN,2019-01-01,7021.0,Bay St / Albert St,43.653264,-79.382458,7233.0,King / Cowan Ave - SMART,43.637922,-79.431734
1,4581279.0,1112.0,7160.0,01/01/2019 00:10,King St W / Tecumseth St,7051.0,01/01/2019 00:29,Wellesley St E / Yonge St (Green P),2947,Annual Member,NaN,2019-01-01,7160.0,King St W / Tecumseth St,43.643333,-79.405556,7051.0,Wellesley St E / Yonge St (Green P),43.665100,-79.383800
2,4581280.0,589.0,7055.0,01/01/2019 00:15,Jarvis St / Carlton St,7013.0,01/01/2019 00:25,Scott St / The Esplanade,2293,Annual Member,NaN,2019-01-01,7055.0,Jarvis St / Carlton St,43.662070,-79.376170,7013.0,Scott St / The Esplanade,43.646560,-79.375274
3,4581281.0,259.0,7012.0,01/01/2019 00:16,Elizabeth St / Edward St (Bus Terminal),7235.0,01/01/2019 00:20,Bay St / College St (West Side) - SMART,283,Annual Member,NaN,2019-01-01,7012.0,Elizabeth St / Edward St (Bus Terminal),43.656026,-79.385327,7235.0,Bay St / College St (West Side) - SMART,43.660087,-79.385655
4,4581282.0,281.0,7041.0,01/01/2019 00:19,Edward St / Yonge St,7257.0,01/01/2019 00:24,Dundas St W / St. Patrick St,1799,Annual Member,NaN,2019-01-01,7041.0,Edward St / Yonge St,43.656729,-79.382736,7257.0,Dundas St W / St. Patrick St,43.654517,-79.389532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8925737,14805103.0,372.0,7065.0,12/31/2021 23:56,Dundas St E / Parliament St,7472.0,01/01/2022 00:02,Dundas St E / Victoria St,3487,Casual Member,NaN,2021-12-31,7065.0,Dundas St E / Parliament St,43.659575,-79.365769,7472.0,Dundas St E / Victoria St,43.656311,-79.379158
8925738,14805104.0,762.0,7233.0,12/31/2021 23:56,King / Cowan Ave - SMART,7569.0,01/01/2022 00:08,Toronto Inukshuk Park,4195,Annual Member,NaN,2021-12-31,7233.0,King / Cowan Ave - SMART,43.637922,-79.431734,7569.0,Toronto Inukshuk Park,43.632399,-79.409782
8925739,14805105.0,355.0,7065.0,12/31/2021 23:56,Dundas St E / Parliament St,7472.0,01/01/2022 00:02,Dundas St E / Victoria St,4574,Casual Member,NaN,2021-12-31,7065.0,Dundas St E / Parliament St,43.659575,-79.365769,7472.0,Dundas St E / Victoria St,43.656311,-79.379158
8925740,14805107.0,770.0,7292.0,12/31/2021 23:56,Granby St / Church St - SMART,7076.0,01/01/2022 00:09,York St / Queens Quay W,5879,Annual Member,NaN,2021-12-31,7292.0,Granby St / Church St - SMART,43.661460,-79.378946,7076.0,York St / Queens Quay W,43.640132,-79.380464
8925741,14805108.0,1307.0,7057.0,12/31/2021 23:59,Simcoe St / Wellington St South,7383.0,01/01/2022 00:21,12 Harbour St,1655,Annual Member,NaN,2021-12-31,7057.0,Simcoe St / Wellington St South,43.645857,-79.385365,7383.0,12 Harbour St,43.642564,-79.376200

In [158]:
#fillna
Merged_station_data_df['End Station Name'] = Merged_station_data_df['End Station Name'].fillna(Merged_station_data_df['end_name'])
Merged_station_data_df[Merged_station_data_df['End Station Name'].isna()]

Empty DataFrame
Columns: [ï»¿Trip Id, Trip  Duration, Start Station Id, Start Time, Start Station Name, End Station Id, End Time, End Station Name, Bike Id, User Type, Trip Id, Date, Stat_id, Stat_name, Latitude, Langitude, end_stat_id, end_name, end_lat, end_lon]
Index: []

In [159]:
#make sure no station id is Nan
Merged_station_data_df[Merged_station_data_df['Start Station Id'].isna()|Merged_station_data_df['End Station Id'].isna()]

Empty DataFrame
Columns: [ï»¿Trip Id, Trip  Duration, Start Station Id, Start Time, Start Station Name, End Station Id, End Time, End Station Name, Bike Id, User Type, Trip Id, Date, Stat_id, Stat_name, Latitude, Langitude, end_stat_id, end_name, end_lat, end_lon]
Index: []

In [160]:
#check if there is na latitude and longitude
Merged_station_data_df[Merged_station_data_df['Latitude'].isna()|Merged_station_data_df['Langitude'].isna()]

,ï»¿Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type,Trip Id,Date,Stat_id,Stat_name,Latitude,Langitude,end_stat_id,end_name,end_lat,end_lon
198,4581480.0,639.0,7254.0,01/01/2019 11:01,Borden St / Bloor St W - SMART,7030.0,01/01/2019 11:11,Bay St / Wellesley St W,2978,Annual Member,NaN,2019-01-01,7254.0,Borden St / Bloor St W - SMART,NaN,NaN,7030.0,Bay St / Wellesley St W,43.664088,-79.387095
546,4581829.0,1365.0,7254.0,01/01/2019 15:00,Borden St / Bloor St W - SMART,7383.0,01/01/2019 15:22,12 Harbour St,2924,Annual Member,NaN,2019-01-01,7254.0,Borden St / Bloor St W - SMART,NaN,NaN,7383.0,12 Harbour St,43.642564,-79.376200
668,4581951.0,550.0,7116.0,01/01/2019 16:15,Parliament St / Bloor St E,7055.0,01/01/2019 16:25,Jarvis St / Carlton St,1235,Annual Member,NaN,2019-01-01,7116.0,Parliament St / Bloor St E,NaN,NaN,7055.0,Jarvis St / Carlton St,43.662070,-79.376170
779,4582062.0,1390.0,7254.0,01/01/2019 17:29,Borden St / Bloor St W - SMART,7191.0,01/01/2019 17:53,Central Tech (Harbord St),2498,Annual Member,NaN,2019-01-01,7254.0,Borden St / Bloor St W - SMART,NaN,NaN,7191.0,Central Tech (Harbord St),43.661975,-79.407896
1003,4582287.0,342.0,7254.0,01/01/2019 21:20,Borden St / Bloor St W - SMART,7240.0,01/01/2019 21:26,Bloor St W / Shaw Ave - SMART,866,Annual Member,NaN,2019-01-01,7254.0,Borden St / Bloor St W - SMART,NaN,NaN,7240.0,Bloor St W / Shaw Ave - SMART,43.662403,-79.423098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8847113,14713543.0,361.0,7436.0,12/12/2021 17:38,Shaw St / Dupont St,7357.0,12/12/2021 17:44,Lake Shore Blvd E / Leslie St,4245,Annual Member,NaN,2021-12-12,7436.0,Shaw St / Dupont St,NaN,NaN,7357.0,Lake Shore Blvd E / Leslie St,43.659195,-79.329196
8849541,14716491.0,804.0,7436.0,12/13/2021 09:05,Shaw St / Dupont St,7275.0,12/13/2021 09:18,Queen St W / James St,4246,Annual Member,NaN,2021-12-13,7436.0,Shaw St / Dupont St,NaN,NaN,7275.0,Queen St W / James St,43.652276,-79.380701
8851294,14718446.0,450.0,7436.0,12/13/2021 14:24,Shaw St / Dupont St,7303.0,12/13/2021 14:32,Queen St E / Woodward Ave,2033,Annual Member,NaN,2021-12-13,7436.0,Shaw St / Dupont St,NaN,NaN,7303.0,Queen St E / Woodward Ave,43.665269,-79.319796
8851677,14718870.0,815.0,7436.0,12/13/2021 15:21,Shaw St / Dupont St,7036.0,12/13/2021 15:35,Trinity St /Front St E,414,Annual Member,NaN,2021-12-13,7436.0,Shaw St / Dupont St,NaN,NaN,7036.0,Trinity St /Front St E,43.651318,-79.360230
8858236,14726164.0,2088.0,7436.0,12/14/2021 14:48,Shaw St / Dupont St,7492.0,12/14/2021 15:23,324 Cherry St,4981,Casual Member,NaN,2021-12-14,7436.0,Shaw St / Dupont St,NaN,NaN,7492.0,324 Cherry St,43.648300,-79.355253

In [161]:
#check if there is na data for end station lat or long
Merged_station_data_df[Merged_station_data_df['end_lat'].isna()|Merged_station_data_df['end_lon'].isna()]

,ï»¿Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type,Trip Id,Date,Stat_id,Stat_name,Latitude,Langitude,end_stat_id,end_name,end_lat,end_lon
85,4581367.0,745.0,7017.0,01/01/2019 04:11,Widmer St / Adelaide St W,7254.0,01/01/2019 04:24,Borden St / Bloor St W - SMART,2924,Annual Member,NaN,2019-01-01,7017.0,Widmer St / Adelaide St W,43.647508,-79.391484,7254.0,Borden St / Bloor St W - SMART,NaN,NaN
378,4581660.0,482.0,7129.0,01/01/2019 13:19,Davenport Rd / Avenue Rd,7254.0,01/01/2019 13:27,Borden St / Bloor St W - SMART,2941,Annual Member,NaN,2019-01-01,7129.0,Davenport Rd / Avenue Rd,43.674991,-79.396273,7254.0,Borden St / Bloor St W - SMART,NaN,NaN
509,4581792.0,277.0,7240.0,01/01/2019 14:37,Bloor St W / Shaw Ave - SMART,7254.0,01/01/2019 14:42,Borden St / Bloor St W - SMART,866,Annual Member,NaN,2019-01-01,7240.0,Bloor St W / Shaw Ave - SMART,43.662403,-79.423098,7254.0,Borden St / Bloor St W - SMART,NaN,NaN
632,4581915.0,756.0,7105.0,01/01/2019 15:40,Queen St E / Sackville St,7116.0,01/01/2019 15:52,Parliament St / Bloor St E,1235,Annual Member,NaN,2019-01-01,7105.0,Queen St E / Sackville St,43.656111,-79.361389,7116.0,Parliament St / Bloor St E,NaN,NaN
677,4581960.0,1226.0,7383.0,01/01/2019 16:22,12 Harbour St,7254.0,01/01/2019 16:42,Borden St / Bloor St W - SMART,929,Annual Member,NaN,2019-01-01,7383.0,12 Harbour St,43.642564,-79.376200,7254.0,Borden St / Bloor St W - SMART,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8859697,14727687.0,1316.0,7006.0,12/14/2021 17:33,Bay St / College St (East Side),7436.0,12/14/2021 17:55,Shaw St / Dupont St,6395,Annual Member,NaN,2021-12-14,7006.0,Bay St / College St (East Side),43.660439,-79.385525,7436.0,Shaw St / Dupont St,NaN,NaN
8859993,14728000.0,1800.0,7042.0,12/14/2021 18:01,Sherbourne St / Wellesley St E,7436.0,12/14/2021 18:31,Shaw St / Dupont St,5602,Casual Member,NaN,2021-12-14,7042.0,Sherbourne St / Wellesley St E,43.667300,-79.374000,7436.0,Shaw St / Dupont St,NaN,NaN
8860455,14728476.0,1357.0,7030.0,12/14/2021 18:50,Bay St / Wellesley St W,7436.0,12/14/2021 19:12,Shaw St / Dupont St,1776,Annual Member,NaN,2021-12-14,7030.0,Bay St / Wellesley St W,43.664088,-79.387095,7436.0,Shaw St / Dupont St,NaN,NaN
8861519,14729624.0,151.0,7103.0,12/14/2021 22:11,Jimmie Simpson Park (Queen St E),7436.0,12/14/2021 22:14,Shaw St / Dupont St,4601,Annual Member,NaN,2021-12-14,7103.0,Jimmie Simpson Park (Queen St E),43.660560,-79.343766,7436.0,Shaw St / Dupont St,NaN,NaN
8886506,14759063.0,0.0,7113.0,12/20/2021 09:20,Parliament St / Aberdeen Ave,7436.0,12/20/2021 09:20,Shaw St / Dupont St,3064,Annual Member,NaN,2021-12-20,7113.0,Parliament St / Aberdeen Ave,43.665278,-79.368333,7436.0,Shaw St / Dupont St,NaN,NaN

In [162]:
#check if the data has station name and end station name 
Merged_station_data_df[Merged_station_data_df['Stat_name'].isna()|Merged_station_data_df['end_name'].isna()]

Empty DataFrame
Columns: [ï»¿Trip Id, Trip  Duration, Start Station Id, Start Time, Start Station Name, End Station Id, End Time, End Station Name, Bike Id, User Type, Trip Id, Date, Stat_id, Stat_name, Latitude, Langitude, end_stat_id, end_name, end_lat, end_lon]
Index: []

In [163]:
Merged_station_data_df.dtypes

ï»¿Trip Id            float64
Trip  Duration        float64
Start Station Id      float64
Start Time             object
Start Station Name     object
End Station Id        float64
End Time               object
End Station Name       object
Bike Id                object
User Type              object
Trip Id               float64
Date                   object
Stat_id               float64
Stat_name              object
Latitude              float64
Langitude             float64
end_stat_id           float64
end_name               object
end_lat               float64
end_lon               float64
dtype: object

In [164]:
#drop unnecessary column
Merged_station_data_df=Merged_station_data_df.drop(['ï»¿Trip Id', 'Start Station Id','Start Station Name','End Station Id','End Station Name','Trip Id'], axis = 1)
Merged_station_data_df

,Trip Duration,Start Time,End Time,Bike Id,User Type,Date,Stat_id,Stat_name,Latitude,Langitude,end_stat_id,end_name,end_lat,end_lon
0,1547.0,01/01/2019 00:08,01/01/2019 00:33,1296,Annual Member,2019-01-01,7021.0,Bay St / Albert St,43.653264,-79.382458,7233.0,King / Cowan Ave - SMART,43.637922,-79.431734
1,1112.0,01/01/2019 00:10,01/01/2019 00:29,2947,Annual Member,2019-01-01,7160.0,King St W / Tecumseth St,43.643333,-79.405556,7051.0,Wellesley St E / Yonge St (Green P),43.665100,-79.383800
2,589.0,01/01/2019 00:15,01/01/2019 00:25,2293,Annual Member,2019-01-01,7055.0,Jarvis St / Carlton St,43.662070,-79.376170,7013.0,Scott St / The Esplanade,43.646560,-79.375274
3,259.0,01/01/2019 00:16,01/01/2019 00:20,283,Annual Member,2019-01-01,7012.0,Elizabeth St / Edward St (Bus Terminal),43.656026,-79.385327,7235.0,Bay St / College St (West Side) - SMART,43.660087,-79.385655
4,281.0,01/01/2019 00:19,01/01/2019 00:24,1799,Annual Member,2019-01-01,7041.0,Edward St / Yonge St,43.656729,-79.382736,7257.0,Dundas St W / St. Patrick St,43.654517,-79.389532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8925737,372.0,12/31/2021 23:56,01/01/2022 00:02,3487,Casual Member,2021-12-31,7065.0,Dundas St E / Parliament St,43.659575,-79.365769,7472.0,Dundas St E / Victoria St,43.656311,-79.379158
8925738,762.0,12/31/2021 23:56,01/01/2022 00:08,4195,Annual Member,2021-12-31,7233.0,King / Cowan Ave - SMART,43.637922,-79.431734,7569.0,Toronto Inukshuk Park,43.632399,-79.409782
8925739,355.0,12/31/2021 23:56,01/01/2022 00:02,4574,Casual Member,2021-12-31,7065.0,Dundas St E / Parliament St,43.659575,-79.365769,7472.0,Dundas St E / Victoria St,43.656311,-79.379158
8925740,770.0,12/31/2021 23:56,01/01/2022 00:09,5879,Annual Member,2021-12-31,7292.0,Granby St / Church St - SMART,43.661460,-79.378946,7076.0,York St / Queens Quay W,43.640132,-79.380464
8925741,1307.0,12/31/2021 23:59,01/01/2022 00:21,1655,Annual Member,2021-12-31,7057.0,Simcoe St / Wellington St South,43.645857,-79.385365,7383.0,12 Harbour St,43.642564,-79.376200

In [165]:
#rename and rearrange column so it will be easier to read
Merged_station_data_df.columns=['r_trip_duration','r_start_time','r_end_time','r_bike_id','r_member_type','r_date','r_start_station_id','r_start_station_name','r_start_lat','r_start_long','r_end_station_id','r_end_station_name','r_end_lat','r_end_long']
Merged_station_data_df_final=Merged_station_data_df[['r_date','r_trip_duration','r_bike_id','r_member_type','r_start_station_id','r_start_station_name','r_start_time','r_start_lat','r_start_long','r_end_station_id','r_end_station_name','r_end_time','r_end_lat','r_end_long']]
Merged_station_data_df_final

,r_date,r_trip_duration,r_bike_id,r_member_type,r_start_station_id,r_start_station_name,r_start_time,r_start_lat,r_start_long,r_end_station_id,r_end_station_name,r_end_time,r_end_lat,r_end_long
0,2019-01-01,1547.0,1296,Annual Member,7021.0,Bay St / Albert St,01/01/2019 00:08,43.653264,-79.382458,7233.0,King / Cowan Ave - SMART,01/01/2019 00:33,43.637922,-79.431734
1,2019-01-01,1112.0,2947,Annual Member,7160.0,King St W / Tecumseth St,01/01/2019 00:10,43.643333,-79.405556,7051.0,Wellesley St E / Yonge St (Green P),01/01/2019 00:29,43.665100,-79.383800
2,2019-01-01,589.0,2293,Annual Member,7055.0,Jarvis St / Carlton St,01/01/2019 00:15,43.662070,-79.376170,7013.0,Scott St / The Esplanade,01/01/2019 00:25,43.646560,-79.375274
3,2019-01-01,259.0,283,Annual Member,7012.0,Elizabeth St / Edward St (Bus Terminal),01/01/2019 00:16,43.656026,-79.385327,7235.0,Bay St / College St (West Side) - SMART,01/01/2019 00:20,43.660087,-79.385655
4,2019-01-01,281.0,1799,Annual Member,7041.0,Edward St / Yonge St,01/01/2019 00:19,43.656729,-79.382736,7257.0,Dundas St W / St. Patrick St,01/01/2019 00:24,43.654517,-79.389532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8925737,2021-12-31,372.0,3487,Casual Member,7065.0,Dundas St E / Parliament St,12/31/2021 23:56,43.659575,-79.365769,7472.0,Dundas St E / Victoria St,01/01/2022 00:02,43.656311,-79.379158
8925738,2021-12-31,762.0,4195,Annual Member,7233.0,King / Cowan Ave - SMART,12/31/2021 23:56,43.637922,-79.431734,7569.0,Toronto Inukshuk Park,01/01/2022 00:08,43.632399,-79.409782
8925739,2021-12-31,355.0,4574,Casual Member,7065.0,Dundas St E / Parliament St,12/31/2021 23:56,43.659575,-79.365769,7472.0,Dundas St E / Victoria St,01/01/2022 00:02,43.656311,-79.379158
8925740,2021-12-31,770.0,5879,Annual Member,7292.0,Granby St / Church St - SMART,12/31/2021 23:56,43.661460,-79.378946,7076.0,York St / Queens Quay W,01/01/2022 00:09,43.640132,-79.380464
8925741,2021-12-31,1307.0,1655,Annual Member,7057.0,Simcoe St / Wellington St South,12/31/2021 23:59,43.645857,-79.385365,7383.0,12 Harbour St,01/01/2022 00:21,43.642564,-79.376200

In [166]:
#save to csv
Merged_station_data_df_final.to_csv('result/tbl_raw_bike_clean.csv',index=False)

In [167]:
#save the csv 
additional_station_df.to_csv('result/tbl_station.csv',index=False)